In [2]:
import numpy as np

x = np.random.randn(3, 3, 3)
x

array([[[ 0.8307994 ,  1.80585952, -0.10534041],
        [ 0.61948665, -0.73957496, -0.42463782],
        [ 0.11566237, -1.15869649, -1.06534124]],

       [[ 0.7725773 ,  0.7065253 ,  0.08894743],
        [-0.27860877, -0.87917348,  1.10874957],
        [ 0.32613251, -0.56006265, -0.62518797]],

       [[ 0.96638578,  0.69061854,  0.01775273],
        [-1.64817091, -0.50041213,  1.68306508],
        [-0.09750055, -1.2604164 ,  0.89608958]]])

In [4]:
np.max(x).shape

()

In [2]:
import numpy as np
n, p = 1, .5  # number of trials, probability of each trial
s = np.random.binomial(n, p, (3, 3))
s

array([[0, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
d = {}
d['a']

KeyError: 'a'

In [1]:
import numpy as np

# Scalar value
scalar_value = 42

# Example NumPy array with a specific dtype
example_array = np.array([1, 2, 3], dtype=np.float64)

# Get the dtype of the example array
desired_dtype = example_array.dtype

# Convert the scalar to the desired dtype
converted_scalar = np.array(scalar_value, dtype=desired_dtype)

print(converted_scalar)

42.0


In [2]:
import numpy as np

'''Notice: dtype is changed when numpy array is a scalar'''
x = np.array(1.2, dtype=np.float32)
x = x / 2
x.dtype

dtype('float64')

In [1]:
import numpy as np

# Create a 2D NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Define the amount of padding for each dimension
pad_width = ((1, 1), (2, 2))  # ((before_1, after_1), (before_2, after_2))

# Specify the padding value (you can use 'constant_values' parameter)
padding_value = 0

# Pad the array
padded_array = np.pad(original_array, pad_width, mode='constant', constant_values=padding_value)

# Print the original and padded arrays
print("Original array:")
print(original_array)
print("\nPadded array:")
print(padded_array)

Original array:
[[1 2 3]
 [4 5 6]]

Padded array:
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]]


In [3]:
import numpy as np
x = np.random.rand(1, 28, 28)
x[0].shape

(28, 28)

In [9]:
x = np.arange(10)
np.random.shuffle(x)
x

array([7, 9, 6, 3, 8, 2, 5, 0, 4, 1])

In [10]:
x = np.random.randn(4, 2)
x

array([[-0.22439764,  0.54993074],
       [ 1.8074708 ,  1.30597443],
       [ 0.04965097,  1.22290137],
       [-0.30485774, -0.36012382]])

In [12]:
i = np.array([3, 1])
x[i]

array([[-0.30485774, -0.36012382],
       [ 1.8074708 ,  1.30597443]])